name: Validate Branches

on:
  push:
    branches-ignore:
      - main

jobs:
  validate:
    if: github.event.repository.fork == false && github.actor != 'dependabot[bot]'
    uses: ./.github/workflows/validate.yml
    secrets:
      ORBIT_PAT: ${{ secrets.ORBIT_PAT }}
    permissions:
      contents: read
